#!/usr/bin/with-contenv bash

echo "Starting Plex Media Server with AMD VAAPI support..."
export PLEX_MEDIA_SERVER_INFO_MODEL=$(uname -m)
export PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION=$(uname -r)
export LD_LIBRARY_PATH=/vaapi-amdgpu/lib
export LIBVA_DRIVERS_PATH=/vaapi-amdgpu/lib/dri
export LIBVA_DRIVER_NAME=radeonsi
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 32400" \
        s6-setuidgid abc "/usr/lib/plexmediaserver/Plex Media Server"
